[profile.default]
src = "contracts"
out = "out"
libs = ["../lib", "node_modules"]
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@mapprotocol/common-contracts/=node_modules/@mapprotocol/common-contracts/',
    "forge-std/=../lib/forge-std/src/"
]

# Solidity compiler settings
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "london"
script = "scripts/foundry"
# Test settings
test = "test"
cache_path = "cache_forge"

# Hardhat compatibility
fs_permissions = [{ access = "read-write", path = "./" }]



[etherscan]
Mapo = { url = "https://explorer-api.chainservice.io/api", key = " "}

[rpc_endpoints]
Mapo = "https://rpc.maplabs.io"    
Makalu = "https://testnet-rpc.maplabs.io"   