[profile.default]
src = "contracts"
out = "out"
libs = ["../lib", "node_modules"]
remappings = [
    '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
    '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
    '@mapprotocol/common-contracts/=node_modules/@mapprotocol/common-contracts/',
    "forge-std/=../lib/forge-std/src/"
]

# Solidity compiler settings
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "london"
script = "scripts/foundry"
# Test settings
test = "test/foundry"
cache_path = "cache_forge"

# Hardhat compatibility
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
Mapo = { url = "https://explorer-api.chainservice.io/api", key = " " }
Eth = { url = "https://api.etherscan.io/v2/api?chainid=1", key = "${ETHERSCAN_API_KEY}" }
Bsc = { url = "https://api.etherscan.io/v2/api?chainid=56", key = "${ETHERSCAN_API_KEY}" }
Base = { url = "https://api.etherscan.io/v2/api?chainid=8453", key = "${ETHERSCAN_API_KEY}" }
Arb = { url = "https://api.etherscan.io/v2/api?chainid=42161", key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
Mapo = "https://rpc.maplabs.io"
Makalu = "https://testnet-rpc.maplabs.io"

Eth = "https://eth-mainnet.public.blastapi.io"
eth_test = "https://1rpc.io/sepolia"

Bsc = "https://binance-smart-chain-public.nodies.app"
bsc_test = "https://bsc-testnet.public.blastapi.io"

Base = "https://1rpc.io/base"
Arb = "https://arb-one.api.pocket.network"